### ISSUE TITLE
Binary State Pins

### ISSUE THREAD

**Issue by avlec** [Fattorino/ImNodeFlow#11]
Natively support pins of type `bool`

**Comment by Fattorino** [comment]
Can't you use `addIN<bool>`? Have I missed something?

**Comment by avlec** [comment]
More the connection filter portion. This currently seems to fall under "Custom"

**Comment by Fattorino** [comment]
ohh yeah right, I'll add a filter for bool

**Comment by Fattorino** [comment]
Closed by commit c1b1c51c0a7710430beee4e8ceadc9d3a264ddfa
