### ISSUE TITLE
The deletion of a node cause a crash

### ISSUE THREAD

**Issue by aiekick** [Fattorino/ImNodeFlow#15]
Hello,

thanks for this good lib.

btw when you delete a node by using the key "delete", cause a crash.

its because you destroy a node from him internally while iterated from a loop.
```cpp
m_inf->getNodes().erase(m_uid)
```
Destroying a node internally via a global pointer is a dangerous behavior, and here cause the issue.
after that line, m_inf point on a release memory and cause the crash for next calls after line 186 of ImFlowNode.cpp

for me, 
you need to mark a node as "to delete"
and delete it from the editor after nodes iteration

i have fixed it [here](https://github.com/aiekick/ImGuiPack/blob/master/3rdparty/imgui_imnodeflow/src/ImNodeFlow.cpp#L168) (but maybe not the way you like :) )

ps : a demo app branch can be cool for see how to use it and test it

**Comment by Fattorino** [comment]
Thank you for the suggestion, I'll have a look at your code later today. But for now, I want to direct your attention to `BaseNode::destroy()` because I think that's what you need. Let me know if this helps you.

**Comment by aiekick** [comment]
its not in my code. when i select a node and press the delete key. the crash is coming.

in your BaseNode::update() code :

```cpp
if (ImGui::IsKeyPressed(ImGuiKey_Delete) && !ImGui::IsAnyItemActive() && isSelected())
            destroy();

        bool onHeader = ImGui::IsMouseHoveringRect(offset + m_pos - paddingTL, offset + m_pos + headerSize);
        if (onHeader && mouseClickState)
        {
            m_inf->consumeSingleUseClick();
            m_dragged = true;
            m_inf->draggingNode(true);
        }
```

the crash happen at "m_inf->consumeSingleUseClick();" because the node was destroyed so m_inf point to a bad adress

For me this code is bad, and the crash is logic.
So if you dont have the issue, its because you may have another objects who is saving the shader_ptr<BaseNode> of m_nodes outside of your lib. this is why you have this curious variable m_destroyed...

in my case, the shared_ptr<BaseNode> in only in m_nodes, so the destroy cause the invalidate of the rest of the code and the crash when we call m_inf->what_you_want

**Comment by Fattorino** [comment]
Ok, now I know what went wrong, when I changed a few things for the latest release I forgot to fix one thing. I'll do it by the end of today

**Comment by aiekick** [comment]
np, thanks

**Comment by Fattorino** [comment]
Fixed with commit 8fee461, now included in latest release `v1.2.1`

**Comment by aiekick** [comment]
Thanks for your quick fix.
and sorry for my agressivity :)

**Comment by Fattorino** [comment]
don't even worry about it
