### ISSUE TITLE
CPP20

### ISSUE THREAD

**Issue by aiekick** [Fattorino/ImNodeFlow#16]
Hello,

please add in your documentation than your lib is requiring c++20 at least.

and maybe other minimal requirements

**Comment by Fattorino** [comment]
Closed with commit d45ad31

**Comment by Fattorino** [comment]
C20 is actually just needed for `std::erase_if`, should I just do it manually and go back to requiring C17 if not lower?

**Comment by aiekick** [comment]
i seen the std::erase_if. 

its like you want. 

in my case all my libs are guarantying a minimal of cpp11 (else absolutely needed like for the api filesystem of cpp17), because i noticed than many of my users have project running only on cpp11.

but its like you want, since you are the creator you can do what you want :)

its just appear to me, than all node libs i can find are not exactly what i need, in features, in dependencies, of logics. So i decided to create my own. based on your work, and the ones of @CedricGuillemet , @Nelarius and @Thedmd (i was using this last from 4 years now, and abandonned because tired to merge manually the stacklayout api used by it in imgui myself..)

**Comment by Fattorino** [comment]
well, thanks for the feedback

**Comment by aiekick** [comment]
I think about what i said, and i think the true reason for why i support at least cpp11 is :
its important for a lib based on and for Dear ImGui to support at least the same standard as ImGui himself. 
Here the fist not compatible func you are suing is std::erase_if, except that, the rest is ok for cpp11

**Comment by Fattorino** [comment]
then it's decided, I'll remove the rather unnecessary `std::erase_if`

**Comment by Fattorino** [comment]
reopened just for the todo list

**Comment by Fattorino** [comment]
closed once again with commit 0ed793d1991df938a97b4fbfa5b66877cfc69783

**Comment by Fattorino** [comment]
Idk where to ask so I'll do it here. @aiekick 
I'm pretty new to CMake, so I'd appreciate a quick feedback on what I can improve about the CMakeList of this project, thanks

**Comment by aiekick** [comment]
you CMakeLists.txt is ok to me.

btw i notices than some users want to compile imgui libs as shared, and in this case you need to have some modification like : 
- provide a API define
- adapt your CMakeLists.txt
- adapt your H

ex : 

in your CMakeLists.txt 
```cmake

if (BUILD_SHARED_LIBS)
	target_compile_definitions(ImNodeFlow INTERFACE BUILD_IM_NODE_FLOW_SHARED_LIBS)
endif()
```

if you do that cmake will produce a define :
* "ImNodeFlow_EXPORTS" for the export
* "BUILD_IM_NODE_FLOW_SHARED_LIBS" for the import

if you like you can specify that explictly like i done for some old libs :
```cmake
target_compile_definitions(glad PUBLIC IM_NODE_FLOW_EXPORT PRIVATE BUILD_IM_NODE_FLOW_SHARED_LIBS)
```
if you do that cmake will produce a define :
* "IM_NODE_FLOW_EXPORT " for the export
* "BUILD_IM_NODE_FLOW_SHARED_LIBS" for the import

indeed you can name that as you want :)

in you h you need a specific code just for windows.
ex what i do in my code (can be simplified)
btw i know there is an equivalent code for gcc, but in my tests i have not noticed any requirement to have some __declspec(dllexport) orr __declspec(dllimport) equivalent code, so maybe for old version of linux :)

```cpp
#if defined(__WIN32__) || defined(WIN32) || defined(_WIN32) || defined(__WIN64__) || defined(WIN64) || defined(_WIN64) || defined(_MSC_VER)
#if defined(ImNodeFlow_EXPORTS)
  #define IM_NODE_FLOW_API __declspec(dllexport)
#elif defined(BUILD_IM_NODE_FLOW_SHARED_LIBS)
  #define IM_NODE_FLOW_API __declspec(dllimport)
#else
  #define IM_NODE_FLOW_API
#endif
#else
  #define IM_NODE_FLOW_API
#endif
```

**Comment by Fattorino** [comment]
Thanks a lot, I'll be looking to improve the configuration in the future then
