### ISSUE TITLE
Documentation/sample about linking nodes programmatically

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Fattorino/ImNodeFlow#21]
Some things seems to be missing from the actual documentation like the possibility to add links programmatically to nodes.
I need to serialize and deserialize nodegraphs so I need to recreate connections programmatically.

It would be great to have a more complex example that show off the entire api some kind of imgui demo but for imNodeFlow.

**Comment by Fattorino** [comment]
It is possible to create links, this was also visible in the old demo video. It's indeed not very well documented and I'll fix that.
```
auto n = INF.placeNode<DemoNode7>();
auto m = INF.placeNode<DemoNode3>();
n->inPin("Val")->createLink(m->inPin("X"));
```
this is a little snapshot from my testing code, I hope this helps

**Comment by Fattorino** [comment]
Did the code snippet work for you? Also, how is it going with the nodes serialization and deserialization?

**Comment by Paolo-Oliverio** [comment]
Code worked great , serialization is on backlog I don't think it will be an issue. 
I'm pretty busy at the moment with business logic so frontend is on pause.
A major pain point is the issue about rendering many nodes , it shouldn't be hard to fix but I touched imgui rendering too long ago to find a quick solution.

**Comment by Fattorino** [comment]
Will be added in future example folder
