### ISSUE TITLE
Minimal example?

### ISSUE THREAD

**Issue by aloneguid** [Fattorino/ImNodeFlow#28]
Can someone please give a minimal working sample on how to use this library. Readme has a code on how to create a custom node, what about something that just works? I've searched codebase here with no success.

**Comment by Fattorino** [comment]
A fully working code example is on the long-term to-do list.
Please reference the documentation. After copying the example node, check out [HANDLER](https://github.com/Fattorino/ImNodeFlow/blob/master/documentation.md#handler)

**Comment by QiuYilin** [comment]
It may be helpful to provide a temporary example first and then replace it with a complete example. A runnable example is the best way to help understanding the library.
