### ISSUE TITLE
Need help with the window that the grid within

### ISSUE THREAD

**Issue by ThorMalleuson** [Fattorino/ImNodeFlow#31]
I am new to ImGUI, but it has been pretty easy to figure out. What I am not figuring out is changing the size of the window that the grid is rendered in. Or in setting its position.  Before calling the ImNodeFlow::update(), I have the following to maximize the window:

const ImGuiViewport* MainViewport = ImGui::GetMainViewport();
ImGui::SetNextWindowPos(ImVec2(0, 0), ImGuiCond_FirstUseEver);
ImGui::SetNextWindowSize(MainViewport->Size, ImGuiCond_FirstUseEver);

But the ImGUI window for ImNodeFlow never matches the size of main viewport. What am I doing wrong? Thank you.

![image](https://github.com/user-attachments/assets/90d349d0-9bfb-4976-b209-f6353849356b)

**Comment by Fattorino** [comment]
ImNodeFlow::update() does not call ImGui::Begin(). You must create a window yourself and inside that call the update function, and then by default it will occupy as much space as possible

**Comment by ThorMalleuson** [comment]
Ah, thank you. That explains my confusion. Thank you for the quick response.
